apiVersion: v1
kind: Namespace
metadata:
  name: gwen-demo-prod
  labels:
    environmentId: env_b457b078-e424-434b-b5eb-e1996b2c4ae0
    projectId: project_8c277afa-6da6-43c2-baaa-25f964829909
    projectName: gwen-demo
    environmentName: prod
    organizationId: org_d2ea4601-f582-4e43-921d-6a60eea704b3
